#pragma once
#include <stdio.h>
#include <iostream>
#include <Windows.h>
#include <stdio.h>
#include <VersionHelpers.h>
#include <cstdio>
#include <tlhelp32.h>
#include <iostream>
#include <fstream>
#include <iostream>
#include <chrono>
#include <thread>
#include <cstdlib>
#include <string>
//string mypip;
//string myos;
//string mycmd;
//string mywebsite;
//string mycore;
//string myadmin;
//string myconsole;
